//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/field/BaseDurationField.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BaseDurationField")
#ifdef RESTRICT_BaseDurationField
#define INCLUDE_ALL_BaseDurationField 0
#else
#define INCLUDE_ALL_BaseDurationField 1
#endif
#undef RESTRICT_BaseDurationField

#if !defined (OrgJodaTimeFieldBaseDurationField_) && (INCLUDE_ALL_BaseDurationField || defined(INCLUDE_OrgJodaTimeFieldBaseDurationField))
#define OrgJodaTimeFieldBaseDurationField_

#define RESTRICT_DurationField 1
#define INCLUDE_OrgJodaTimeDurationField 1
#include "DurationField.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class OrgJodaTimeDurationFieldType;

@interface OrgJodaTimeFieldBaseDurationField : OrgJodaTimeDurationField < JavaIoSerializable >

#pragma mark Public

- (jint)compareToWithId:(OrgJodaTimeDurationField *)otherField;

- (jint)getDifferenceWithLong:(jlong)minuendInstant
                     withLong:(jlong)subtrahendInstant;

- (jlong)getMillisWithInt:(jint)value;

- (jlong)getMillisWithLong:(jlong)value;

- (NSString *)getName;

- (OrgJodaTimeDurationFieldType *)getType;

- (jint)getValueWithLong:(jlong)duration;

- (jint)getValueWithLong:(jlong)duration
                withLong:(jlong)instant;

- (jlong)getValueAsLongWithLong:(jlong)duration;

- (jboolean)isSupported;

- (NSString *)description;

#pragma mark Protected

- (instancetype)initWithOrgJodaTimeDurationFieldType:(OrgJodaTimeDurationFieldType *)type;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeFieldBaseDurationField)

FOUNDATION_EXPORT void OrgJodaTimeFieldBaseDurationField_initWithOrgJodaTimeDurationFieldType_(OrgJodaTimeFieldBaseDurationField *self, OrgJodaTimeDurationFieldType *type);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeFieldBaseDurationField)

#endif

#pragma pop_macro("INCLUDE_ALL_BaseDurationField")
