//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/base/BaseLocal.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BaseLocal")
#ifdef RESTRICT_BaseLocal
#define INCLUDE_ALL_BaseLocal 0
#else
#define INCLUDE_ALL_BaseLocal 1
#endif
#undef RESTRICT_BaseLocal

#if !defined (OrgJodaTimeBaseBaseLocal_) && (INCLUDE_ALL_BaseLocal || defined(INCLUDE_OrgJodaTimeBaseBaseLocal))
#define OrgJodaTimeBaseBaseLocal_

#define RESTRICT_AbstractPartial 1
#define INCLUDE_OrgJodaTimeBaseAbstractPartial 1
#include "AbstractPartial.h"

@interface OrgJodaTimeBaseBaseLocal : OrgJodaTimeBaseAbstractPartial

#pragma mark Protected

- (instancetype)init;

- (jlong)getLocalMillis;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeBaseBaseLocal)

FOUNDATION_EXPORT void OrgJodaTimeBaseBaseLocal_init(OrgJodaTimeBaseBaseLocal *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeBaseBaseLocal)

#endif

#pragma pop_macro("INCLUDE_ALL_BaseLocal")
