//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/chrono/BasicChronology.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BasicChronology")
#ifdef RESTRICT_BasicChronology
#define INCLUDE_ALL_BasicChronology 0
#else
#define INCLUDE_ALL_BasicChronology 1
#endif
#undef RESTRICT_BasicChronology

#if !defined (OrgJodaTimeChronoBasicChronology_) && (INCLUDE_ALL_BasicChronology || defined(INCLUDE_OrgJodaTimeChronoBasicChronology))
#define OrgJodaTimeChronoBasicChronology_

#define RESTRICT_AssembledChronology 1
#define INCLUDE_OrgJodaTimeChronoAssembledChronology 1
#include "AssembledChronology.h"

@class OrgJodaTimeChronoAssembledChronology_Fields;
@class OrgJodaTimeChronology;
@class OrgJodaTimeDateTimeZone;

@interface OrgJodaTimeChronoBasicChronology : OrgJodaTimeChronoAssembledChronology

#pragma mark Public

- (jboolean)isEqual:(id)obj;

- (jlong)getDateTimeMillisWithInt:(jint)year
                          withInt:(jint)monthOfYear
                          withInt:(jint)dayOfMonth
                          withInt:(jint)millisOfDay;

- (jlong)getDateTimeMillisWithInt:(jint)year
                          withInt:(jint)monthOfYear
                          withInt:(jint)dayOfMonth
                          withInt:(jint)hourOfDay
                          withInt:(jint)minuteOfHour
                          withInt:(jint)secondOfMinute
                          withInt:(jint)millisOfSecond;

- (jint)getMinimumDaysInFirstWeek;

- (OrgJodaTimeDateTimeZone *)getZone;

- (NSUInteger)hash;

- (NSString *)description;

#pragma mark Protected

- (void)assembleWithOrgJodaTimeChronoAssembledChronology_Fields:(OrgJodaTimeChronoAssembledChronology_Fields *)fields;

#pragma mark Package-Private

- (instancetype)initWithOrgJodaTimeChronology:(OrgJodaTimeChronology *)base
                                       withId:(id)param
                                      withInt:(jint)minDaysInFirstWeek;

- (jlong)calculateFirstDayOfYearMillisWithInt:(jint)year;

- (jlong)getApproxMillisAtEpochDividedByTwo;

- (jlong)getAverageMillisPerMonth;

- (jlong)getAverageMillisPerYear;

- (jlong)getAverageMillisPerYearDividedByTwo;

- (jlong)getDateMidnightMillisWithInt:(jint)year
                              withInt:(jint)monthOfYear
                              withInt:(jint)dayOfMonth;

- (jint)getDayOfMonthWithLong:(jlong)millis;

- (jint)getDayOfMonthWithLong:(jlong)millis
                      withInt:(jint)year;

- (jint)getDayOfMonthWithLong:(jlong)millis
                      withInt:(jint)year
                      withInt:(jint)month;

- (jint)getDayOfWeekWithLong:(jlong)instant;

- (jint)getDayOfYearWithLong:(jlong)instant;

- (jint)getDayOfYearWithLong:(jlong)instant
                     withInt:(jint)year;

- (jint)getDaysInMonthMax;

- (jint)getDaysInMonthMaxWithInt:(jint)month;

- (jint)getDaysInMonthMaxWithLong:(jlong)instant;

- (jint)getDaysInMonthMaxForSetWithLong:(jlong)instant
                                withInt:(jint)value;

- (jint)getDaysInYearWithInt:(jint)year;

- (jint)getDaysInYearMax;

- (jint)getDaysInYearMonthWithInt:(jint)year
                          withInt:(jint)month;

- (jlong)getFirstWeekOfYearMillisWithInt:(jint)year;

- (jint)getMaxMonth;

- (jint)getMaxMonthWithInt:(jint)year;

- (jint)getMaxYear;

- (jint)getMillisOfDayWithLong:(jlong)instant;

- (jint)getMinYear;

- (jint)getMonthOfYearWithLong:(jlong)millis;

- (jint)getMonthOfYearWithLong:(jlong)millis
                       withInt:(jint)year;

- (jlong)getTotalMillisByYearMonthWithInt:(jint)year
                                  withInt:(jint)month;

- (jint)getWeekOfWeekyearWithLong:(jlong)instant;

- (jint)getWeekOfWeekyearWithLong:(jlong)instant
                          withInt:(jint)year;

- (jint)getWeeksInYearWithInt:(jint)year;

- (jint)getWeekyearWithLong:(jlong)instant;

- (jint)getYearWithLong:(jlong)instant;

- (jlong)getYearDifferenceWithLong:(jlong)minuendInstant
                          withLong:(jlong)subtrahendInstant;

- (jlong)getYearMillisWithInt:(jint)year;

- (jlong)getYearMonthDayMillisWithInt:(jint)year
                              withInt:(jint)month
                              withInt:(jint)dayOfMonth;

- (jlong)getYearMonthMillisWithInt:(jint)year
                           withInt:(jint)month;

- (jboolean)isLeapDayWithLong:(jlong)instant;

- (jboolean)isLeapYearWithInt:(jint)year;

- (jlong)setYearWithLong:(jlong)instant
                 withInt:(jint)year;

@end

J2OBJC_STATIC_INIT(OrgJodaTimeChronoBasicChronology)

FOUNDATION_EXPORT void OrgJodaTimeChronoBasicChronology_initWithOrgJodaTimeChronology_withId_withInt_(OrgJodaTimeChronoBasicChronology *self, OrgJodaTimeChronology *base, id param, jint minDaysInFirstWeek);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeChronoBasicChronology)

#endif

#pragma pop_macro("INCLUDE_ALL_BasicChronology")
