//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/format/DateTimeFormatter.java
//

#include "Chronology.h"
#include "DateTime.h"
#include "DateTimeField.h"
#include "DateTimeFormatter.h"
#include "DateTimeParser.h"
#include "DateTimeParserBucket.h"
#include "DateTimeParserInternalParser.h"
#include "DateTimePrinter.h"
#include "DateTimePrinterInternalPrinter.h"
#include "DateTimeUtils.h"
#include "DateTimeZone.h"
#include "FormatUtils.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "InternalParser.h"
#include "InternalParserDateTimeParser.h"
#include "InternalPrinter.h"
#include "InternalPrinterDateTimePrinter.h"
#include "J2ObjC_source.h"
#include "LocalDate.h"
#include "LocalDateTime.h"
#include "LocalTime.h"
#include "MutableDateTime.h"
#include "ReadWritableInstant.h"
#include "ReadableInstant.h"
#include "ReadablePartial.h"
#include "java/io/IOException.h"
#include "java/io/Writer.h"
#include "java/lang/Appendable.h"
#include "java/lang/Deprecated.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Integer.h"
#include "java/lang/StringBuffer.h"
#include "java/lang/StringBuilder.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/lang/annotation/Annotation.h"
#include "java/util/Locale.h"

@interface OrgJodaTimeFormatDateTimeFormatter () {
 @public
  id<OrgJodaTimeFormatInternalPrinter> iPrinter_;
  id<OrgJodaTimeFormatInternalParser> iParser_;
  JavaUtilLocale *iLocale_;
  jboolean iOffsetParsed_;
  OrgJodaTimeChronology *iChrono_;
  OrgJodaTimeDateTimeZone *iZone_;
  JavaLangInteger *iPivotYear_;
  jint iDefaultYear_;
}

- (instancetype)initWithOrgJodaTimeFormatInternalPrinter:(id<OrgJodaTimeFormatInternalPrinter>)printer
                     withOrgJodaTimeFormatInternalParser:(id<OrgJodaTimeFormatInternalParser>)parser
                                      withJavaUtilLocale:(JavaUtilLocale *)locale
                                             withBoolean:(jboolean)offsetParsed
                               withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono
                             withOrgJodaTimeDateTimeZone:(OrgJodaTimeDateTimeZone *)zone
                                     withJavaLangInteger:(JavaLangInteger *)pivotYear
                                                 withInt:(jint)defaultYear;

- (void)printToWithJavaLangAppendable:(id<JavaLangAppendable>)appendable
                             withLong:(jlong)instant
            withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

- (id<OrgJodaTimeFormatInternalPrinter>)requirePrinter;

- (id<OrgJodaTimeFormatInternalParser>)requireParser;

- (OrgJodaTimeChronology *)selectChronologyWithOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

@end

J2OBJC_FIELD_SETTER(OrgJodaTimeFormatDateTimeFormatter, iPrinter_, id<OrgJodaTimeFormatInternalPrinter>)
J2OBJC_FIELD_SETTER(OrgJodaTimeFormatDateTimeFormatter, iParser_, id<OrgJodaTimeFormatInternalParser>)
J2OBJC_FIELD_SETTER(OrgJodaTimeFormatDateTimeFormatter, iLocale_, JavaUtilLocale *)
J2OBJC_FIELD_SETTER(OrgJodaTimeFormatDateTimeFormatter, iChrono_, OrgJodaTimeChronology *)
J2OBJC_FIELD_SETTER(OrgJodaTimeFormatDateTimeFormatter, iZone_, OrgJodaTimeDateTimeZone *)
J2OBJC_FIELD_SETTER(OrgJodaTimeFormatDateTimeFormatter, iPivotYear_, JavaLangInteger *)

__attribute__((unused)) static void OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(OrgJodaTimeFormatDateTimeFormatter *self, id<OrgJodaTimeFormatInternalPrinter> printer, id<OrgJodaTimeFormatInternalParser> parser, JavaUtilLocale *locale, jboolean offsetParsed, OrgJodaTimeChronology *chrono, OrgJodaTimeDateTimeZone *zone, JavaLangInteger *pivotYear, jint defaultYear);

__attribute__((unused)) static OrgJodaTimeFormatDateTimeFormatter *new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(id<OrgJodaTimeFormatInternalPrinter> printer, id<OrgJodaTimeFormatInternalParser> parser, JavaUtilLocale *locale, jboolean offsetParsed, OrgJodaTimeChronology *chrono, OrgJodaTimeDateTimeZone *zone, JavaLangInteger *pivotYear, jint defaultYear) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgJodaTimeFormatDateTimeFormatter *create_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(id<OrgJodaTimeFormatInternalPrinter> printer, id<OrgJodaTimeFormatInternalParser> parser, JavaUtilLocale *locale, jboolean offsetParsed, OrgJodaTimeChronology *chrono, OrgJodaTimeDateTimeZone *zone, JavaLangInteger *pivotYear, jint defaultYear);

__attribute__((unused)) static void OrgJodaTimeFormatDateTimeFormatter_printToWithJavaLangAppendable_withLong_withOrgJodaTimeChronology_(OrgJodaTimeFormatDateTimeFormatter *self, id<JavaLangAppendable> appendable, jlong instant, OrgJodaTimeChronology *chrono);

__attribute__((unused)) static id<OrgJodaTimeFormatInternalPrinter> OrgJodaTimeFormatDateTimeFormatter_requirePrinter(OrgJodaTimeFormatDateTimeFormatter *self);

__attribute__((unused)) static id<OrgJodaTimeFormatInternalParser> OrgJodaTimeFormatDateTimeFormatter_requireParser(OrgJodaTimeFormatDateTimeFormatter *self);

__attribute__((unused)) static OrgJodaTimeChronology *OrgJodaTimeFormatDateTimeFormatter_selectChronologyWithOrgJodaTimeChronology_(OrgJodaTimeFormatDateTimeFormatter *self, OrgJodaTimeChronology *chrono);

__attribute__((unused)) static IOSObjectArray *OrgJodaTimeFormatDateTimeFormatter__Annotations$0();

@implementation OrgJodaTimeFormatDateTimeFormatter

- (instancetype)initWithOrgJodaTimeFormatDateTimePrinter:(id<OrgJodaTimeFormatDateTimePrinter>)printer
                     withOrgJodaTimeFormatDateTimeParser:(id<OrgJodaTimeFormatDateTimeParser>)parser {
  OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatDateTimePrinter_withOrgJodaTimeFormatDateTimeParser_(self, printer, parser);
  return self;
}

- (instancetype)initWithOrgJodaTimeFormatInternalPrinter:(id<OrgJodaTimeFormatInternalPrinter>)printer
                     withOrgJodaTimeFormatInternalParser:(id<OrgJodaTimeFormatInternalParser>)parser {
  OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_(self, printer, parser);
  return self;
}

- (instancetype)initWithOrgJodaTimeFormatInternalPrinter:(id<OrgJodaTimeFormatInternalPrinter>)printer
                     withOrgJodaTimeFormatInternalParser:(id<OrgJodaTimeFormatInternalParser>)parser
                                      withJavaUtilLocale:(JavaUtilLocale *)locale
                                             withBoolean:(jboolean)offsetParsed
                               withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono
                             withOrgJodaTimeDateTimeZone:(OrgJodaTimeDateTimeZone *)zone
                                     withJavaLangInteger:(JavaLangInteger *)pivotYear
                                                 withInt:(jint)defaultYear {
  OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(self, printer, parser, locale, offsetParsed, chrono, zone, pivotYear, defaultYear);
  return self;
}

- (jboolean)isPrinter {
  return (iPrinter_ != nil);
}

- (id<OrgJodaTimeFormatDateTimePrinter>)getPrinter {
  return OrgJodaTimeFormatInternalPrinterDateTimePrinter_ofWithOrgJodaTimeFormatInternalPrinter_(iPrinter_);
}

- (id<OrgJodaTimeFormatInternalPrinter>)getPrinter0 {
  return iPrinter_;
}

- (jboolean)isParser {
  return (iParser_ != nil);
}

- (id<OrgJodaTimeFormatDateTimeParser>)getParser {
  return OrgJodaTimeFormatInternalParserDateTimeParser_ofWithOrgJodaTimeFormatInternalParser_(iParser_);
}

- (id<OrgJodaTimeFormatInternalParser>)getParser0 {
  return iParser_;
}

- (OrgJodaTimeFormatDateTimeFormatter *)withLocaleWithJavaUtilLocale:(JavaUtilLocale *)locale {
  if (locale == [self getLocale] || (locale != nil && [locale isEqual:[self getLocale]])) {
    return self;
  }
  return new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(iPrinter_, iParser_, locale, iOffsetParsed_, iChrono_, iZone_, iPivotYear_, iDefaultYear_);
}

- (JavaUtilLocale *)getLocale {
  return iLocale_;
}

- (OrgJodaTimeFormatDateTimeFormatter *)withOffsetParsed {
  if (iOffsetParsed_ == true) {
    return self;
  }
  return new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(iPrinter_, iParser_, iLocale_, true, iChrono_, nil, iPivotYear_, iDefaultYear_);
}

- (jboolean)isOffsetParsed {
  return iOffsetParsed_;
}

- (OrgJodaTimeFormatDateTimeFormatter *)withChronologyWithOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono {
  if (iChrono_ == chrono) {
    return self;
  }
  return new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(iPrinter_, iParser_, iLocale_, iOffsetParsed_, chrono, iZone_, iPivotYear_, iDefaultYear_);
}

- (OrgJodaTimeChronology *)getChronology {
  return iChrono_;
}

- (OrgJodaTimeChronology *)getChronolgy {
  return iChrono_;
}

- (OrgJodaTimeFormatDateTimeFormatter *)withZoneUTC {
  return [self withZoneWithOrgJodaTimeDateTimeZone:JreLoadStatic(OrgJodaTimeDateTimeZone, UTC)];
}

- (OrgJodaTimeFormatDateTimeFormatter *)withZoneWithOrgJodaTimeDateTimeZone:(OrgJodaTimeDateTimeZone *)zone {
  if (iZone_ == zone) {
    return self;
  }
  return new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(iPrinter_, iParser_, iLocale_, false, iChrono_, zone, iPivotYear_, iDefaultYear_);
}

- (OrgJodaTimeDateTimeZone *)getZone {
  return iZone_;
}

- (OrgJodaTimeFormatDateTimeFormatter *)withPivotYearWithJavaLangInteger:(JavaLangInteger *)pivotYear {
  if (iPivotYear_ == pivotYear || (iPivotYear_ != nil && [iPivotYear_ isEqual:pivotYear])) {
    return self;
  }
  return new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(iPrinter_, iParser_, iLocale_, iOffsetParsed_, iChrono_, iZone_, pivotYear, iDefaultYear_);
}

- (OrgJodaTimeFormatDateTimeFormatter *)withPivotYearWithInt:(jint)pivotYear {
  return [self withPivotYearWithJavaLangInteger:JavaLangInteger_valueOfWithInt_(pivotYear)];
}

- (JavaLangInteger *)getPivotYear {
  return iPivotYear_;
}

- (OrgJodaTimeFormatDateTimeFormatter *)withDefaultYearWithInt:(jint)defaultYear {
  return new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(iPrinter_, iParser_, iLocale_, iOffsetParsed_, iChrono_, iZone_, iPivotYear_, defaultYear);
}

- (jint)getDefaultYear {
  return iDefaultYear_;
}

- (void)printToWithJavaLangStringBuffer:(JavaLangStringBuffer *)buf
         withOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)instant {
  @try {
    [self printToWithJavaLangAppendable:buf withOrgJodaTimeReadableInstant:instant];
  }
  @catch (JavaIoIOException *ex) {
  }
}

- (void)printToWithJavaLangStringBuilder:(JavaLangStringBuilder *)buf
          withOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)instant {
  @try {
    [self printToWithJavaLangAppendable:buf withOrgJodaTimeReadableInstant:instant];
  }
  @catch (JavaIoIOException *ex) {
  }
}

- (void)printToWithJavaIoWriter:(JavaIoWriter *)outArg
 withOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)instant {
  [self printToWithJavaLangAppendable:outArg withOrgJodaTimeReadableInstant:instant];
}

- (void)printToWithJavaLangAppendable:(id<JavaLangAppendable>)appendable
       withOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)instant {
  jlong millis = OrgJodaTimeDateTimeUtils_getInstantMillisWithOrgJodaTimeReadableInstant_(instant);
  OrgJodaTimeChronology *chrono = OrgJodaTimeDateTimeUtils_getInstantChronologyWithOrgJodaTimeReadableInstant_(instant);
  OrgJodaTimeFormatDateTimeFormatter_printToWithJavaLangAppendable_withLong_withOrgJodaTimeChronology_(self, appendable, millis, chrono);
}

- (void)printToWithJavaLangStringBuffer:(JavaLangStringBuffer *)buf
                               withLong:(jlong)instant {
  @try {
    [self printToWithJavaLangAppendable:buf withLong:instant];
  }
  @catch (JavaIoIOException *ex) {
  }
}

- (void)printToWithJavaLangStringBuilder:(JavaLangStringBuilder *)buf
                                withLong:(jlong)instant {
  @try {
    [self printToWithJavaLangAppendable:buf withLong:instant];
  }
  @catch (JavaIoIOException *ex) {
  }
}

- (void)printToWithJavaIoWriter:(JavaIoWriter *)outArg
                       withLong:(jlong)instant {
  [self printToWithJavaLangAppendable:outArg withLong:instant];
}

- (void)printToWithJavaLangAppendable:(id<JavaLangAppendable>)appendable
                             withLong:(jlong)instant {
  OrgJodaTimeFormatDateTimeFormatter_printToWithJavaLangAppendable_withLong_withOrgJodaTimeChronology_(self, appendable, instant, nil);
}

- (void)printToWithJavaLangStringBuffer:(JavaLangStringBuffer *)buf
         withOrgJodaTimeReadablePartial:(id<OrgJodaTimeReadablePartial>)partial {
  @try {
    [self printToWithJavaLangAppendable:buf withOrgJodaTimeReadablePartial:partial];
  }
  @catch (JavaIoIOException *ex) {
  }
}

- (void)printToWithJavaLangStringBuilder:(JavaLangStringBuilder *)buf
          withOrgJodaTimeReadablePartial:(id<OrgJodaTimeReadablePartial>)partial {
  @try {
    [self printToWithJavaLangAppendable:buf withOrgJodaTimeReadablePartial:partial];
  }
  @catch (JavaIoIOException *ex) {
  }
}

- (void)printToWithJavaIoWriter:(JavaIoWriter *)outArg
 withOrgJodaTimeReadablePartial:(id<OrgJodaTimeReadablePartial>)partial {
  [self printToWithJavaLangAppendable:outArg withOrgJodaTimeReadablePartial:partial];
}

- (void)printToWithJavaLangAppendable:(id<JavaLangAppendable>)appendable
       withOrgJodaTimeReadablePartial:(id<OrgJodaTimeReadablePartial>)partial {
  id<OrgJodaTimeFormatInternalPrinter> printer = OrgJodaTimeFormatDateTimeFormatter_requirePrinter(self);
  if (partial == nil) {
    @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"The partial must not be null");
  }
  [((id<OrgJodaTimeFormatInternalPrinter>) nil_chk(printer)) printToWithJavaLangAppendable:appendable withOrgJodaTimeReadablePartial:partial withJavaUtilLocale:iLocale_];
}

- (NSString *)printWithOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)instant {
  JavaLangStringBuilder *buf = new_JavaLangStringBuilder_initWithInt_([((id<OrgJodaTimeFormatInternalPrinter>) nil_chk(OrgJodaTimeFormatDateTimeFormatter_requirePrinter(self))) estimatePrintedLength]);
  @try {
    [self printToWithJavaLangAppendable:buf withOrgJodaTimeReadableInstant:instant];
  }
  @catch (JavaIoIOException *ex) {
  }
  return [buf description];
}

- (NSString *)printWithLong:(jlong)instant {
  JavaLangStringBuilder *buf = new_JavaLangStringBuilder_initWithInt_([((id<OrgJodaTimeFormatInternalPrinter>) nil_chk(OrgJodaTimeFormatDateTimeFormatter_requirePrinter(self))) estimatePrintedLength]);
  @try {
    [self printToWithJavaLangAppendable:buf withLong:instant];
  }
  @catch (JavaIoIOException *ex) {
  }
  return [buf description];
}

- (NSString *)printWithOrgJodaTimeReadablePartial:(id<OrgJodaTimeReadablePartial>)partial {
  JavaLangStringBuilder *buf = new_JavaLangStringBuilder_initWithInt_([((id<OrgJodaTimeFormatInternalPrinter>) nil_chk(OrgJodaTimeFormatDateTimeFormatter_requirePrinter(self))) estimatePrintedLength]);
  @try {
    [self printToWithJavaLangAppendable:buf withOrgJodaTimeReadablePartial:partial];
  }
  @catch (JavaIoIOException *ex) {
  }
  return [buf description];
}

- (void)printToWithJavaLangAppendable:(id<JavaLangAppendable>)appendable
                             withLong:(jlong)instant
            withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono {
  OrgJodaTimeFormatDateTimeFormatter_printToWithJavaLangAppendable_withLong_withOrgJodaTimeChronology_(self, appendable, instant, chrono);
}

- (id<OrgJodaTimeFormatInternalPrinter>)requirePrinter {
  return OrgJodaTimeFormatDateTimeFormatter_requirePrinter(self);
}

- (jint)parseIntoWithOrgJodaTimeReadWritableInstant:(id<OrgJodaTimeReadWritableInstant>)instant
                                       withNSString:(NSString *)text
                                            withInt:(jint)position {
  id<OrgJodaTimeFormatInternalParser> parser = OrgJodaTimeFormatDateTimeFormatter_requireParser(self);
  if (instant == nil) {
    @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"Instant must not be null");
  }
  jlong instantMillis = [instant getMillis];
  OrgJodaTimeChronology *chrono = [instant getChronology];
  jint defaultYear = [((OrgJodaTimeDateTimeField *) nil_chk([((OrgJodaTimeChronology *) nil_chk(OrgJodaTimeDateTimeUtils_getChronologyWithOrgJodaTimeChronology_(chrono))) year])) getWithLong:instantMillis];
  jlong instantLocal = instantMillis + [((OrgJodaTimeDateTimeZone *) nil_chk([((OrgJodaTimeChronology *) nil_chk(chrono)) getZone])) getOffsetWithLong:instantMillis];
  chrono = OrgJodaTimeFormatDateTimeFormatter_selectChronologyWithOrgJodaTimeChronology_(self, chrono);
  OrgJodaTimeFormatDateTimeParserBucket *bucket = new_OrgJodaTimeFormatDateTimeParserBucket_initWithLong_withOrgJodaTimeChronology_withJavaUtilLocale_withJavaLangInteger_withInt_(instantLocal, chrono, iLocale_, iPivotYear_, defaultYear);
  jint newPos = [((id<OrgJodaTimeFormatInternalParser>) nil_chk(parser)) parseIntoWithOrgJodaTimeFormatDateTimeParserBucket:bucket withJavaLangCharSequence:text withInt:position];
  [instant setMillisWithLong:[bucket computeMillisWithBoolean:false withNSString:text]];
  if (iOffsetParsed_ && [bucket getOffsetInteger] != nil) {
    jint parsedOffset = [((JavaLangInteger *) nil_chk([bucket getOffsetInteger])) intValue];
    OrgJodaTimeDateTimeZone *parsedZone = OrgJodaTimeDateTimeZone_forOffsetMillisWithInt_(parsedOffset);
    chrono = [((OrgJodaTimeChronology *) nil_chk(chrono)) withZoneWithOrgJodaTimeDateTimeZone:parsedZone];
  }
  else if ([bucket getZone] != nil) {
    chrono = [((OrgJodaTimeChronology *) nil_chk(chrono)) withZoneWithOrgJodaTimeDateTimeZone:[bucket getZone]];
  }
  [instant setChronologyWithOrgJodaTimeChronology:chrono];
  if (iZone_ != nil) {
    [instant setZoneWithOrgJodaTimeDateTimeZone:iZone_];
  }
  return newPos;
}

- (jlong)parseMillisWithNSString:(NSString *)text {
  id<OrgJodaTimeFormatInternalParser> parser = OrgJodaTimeFormatDateTimeFormatter_requireParser(self);
  OrgJodaTimeChronology *chrono = OrgJodaTimeFormatDateTimeFormatter_selectChronologyWithOrgJodaTimeChronology_(self, iChrono_);
  OrgJodaTimeFormatDateTimeParserBucket *bucket = new_OrgJodaTimeFormatDateTimeParserBucket_initWithLong_withOrgJodaTimeChronology_withJavaUtilLocale_withJavaLangInteger_withInt_(0, chrono, iLocale_, iPivotYear_, iDefaultYear_);
  return [bucket doParseMillisWithOrgJodaTimeFormatInternalParser:parser withJavaLangCharSequence:text];
}

- (OrgJodaTimeLocalDate *)parseLocalDateWithNSString:(NSString *)text {
  return [((OrgJodaTimeLocalDateTime *) nil_chk([self parseLocalDateTimeWithNSString:text])) toLocalDate];
}

- (OrgJodaTimeLocalTime *)parseLocalTimeWithNSString:(NSString *)text {
  return [((OrgJodaTimeLocalDateTime *) nil_chk([self parseLocalDateTimeWithNSString:text])) toLocalTime];
}

- (OrgJodaTimeLocalDateTime *)parseLocalDateTimeWithNSString:(NSString *)text {
  id<OrgJodaTimeFormatInternalParser> parser = OrgJodaTimeFormatDateTimeFormatter_requireParser(self);
  OrgJodaTimeChronology *chrono = [((OrgJodaTimeChronology *) nil_chk(OrgJodaTimeFormatDateTimeFormatter_selectChronologyWithOrgJodaTimeChronology_(self, nil))) withUTC];
  OrgJodaTimeFormatDateTimeParserBucket *bucket = new_OrgJodaTimeFormatDateTimeParserBucket_initWithLong_withOrgJodaTimeChronology_withJavaUtilLocale_withJavaLangInteger_withInt_(0, chrono, iLocale_, iPivotYear_, iDefaultYear_);
  jint newPos = [((id<OrgJodaTimeFormatInternalParser>) nil_chk(parser)) parseIntoWithOrgJodaTimeFormatDateTimeParserBucket:bucket withJavaLangCharSequence:text withInt:0];
  if (newPos >= 0) {
    if (newPos >= ((jint) [((NSString *) nil_chk(text)) length])) {
      jlong millis = [bucket computeMillisWithBoolean:true withNSString:text];
      if ([bucket getOffsetInteger] != nil) {
        jint parsedOffset = [((JavaLangInteger *) nil_chk([bucket getOffsetInteger])) intValue];
        OrgJodaTimeDateTimeZone *parsedZone = OrgJodaTimeDateTimeZone_forOffsetMillisWithInt_(parsedOffset);
        chrono = [((OrgJodaTimeChronology *) nil_chk(chrono)) withZoneWithOrgJodaTimeDateTimeZone:parsedZone];
      }
      else if ([bucket getZone] != nil) {
        chrono = [((OrgJodaTimeChronology *) nil_chk(chrono)) withZoneWithOrgJodaTimeDateTimeZone:[bucket getZone]];
      }
      return new_OrgJodaTimeLocalDateTime_initWithLong_withOrgJodaTimeChronology_(millis, chrono);
    }
  }
  else {
    newPos = ~newPos;
  }
  @throw new_JavaLangIllegalArgumentException_initWithNSString_(OrgJodaTimeFormatFormatUtils_createErrorMessageWithNSString_withInt_(text, newPos));
}

- (OrgJodaTimeDateTime *)parseDateTimeWithNSString:(NSString *)text {
  id<OrgJodaTimeFormatInternalParser> parser = OrgJodaTimeFormatDateTimeFormatter_requireParser(self);
  OrgJodaTimeChronology *chrono = OrgJodaTimeFormatDateTimeFormatter_selectChronologyWithOrgJodaTimeChronology_(self, nil);
  OrgJodaTimeFormatDateTimeParserBucket *bucket = new_OrgJodaTimeFormatDateTimeParserBucket_initWithLong_withOrgJodaTimeChronology_withJavaUtilLocale_withJavaLangInteger_withInt_(0, chrono, iLocale_, iPivotYear_, iDefaultYear_);
  jint newPos = [((id<OrgJodaTimeFormatInternalParser>) nil_chk(parser)) parseIntoWithOrgJodaTimeFormatDateTimeParserBucket:bucket withJavaLangCharSequence:text withInt:0];
  if (newPos >= 0) {
    if (newPos >= ((jint) [((NSString *) nil_chk(text)) length])) {
      jlong millis = [bucket computeMillisWithBoolean:true withNSString:text];
      if (iOffsetParsed_ && [bucket getOffsetInteger] != nil) {
        jint parsedOffset = [((JavaLangInteger *) nil_chk([bucket getOffsetInteger])) intValue];
        OrgJodaTimeDateTimeZone *parsedZone = OrgJodaTimeDateTimeZone_forOffsetMillisWithInt_(parsedOffset);
        chrono = [((OrgJodaTimeChronology *) nil_chk(chrono)) withZoneWithOrgJodaTimeDateTimeZone:parsedZone];
      }
      else if ([bucket getZone] != nil) {
        chrono = [((OrgJodaTimeChronology *) nil_chk(chrono)) withZoneWithOrgJodaTimeDateTimeZone:[bucket getZone]];
      }
      OrgJodaTimeDateTime *dt = new_OrgJodaTimeDateTime_initWithLong_withOrgJodaTimeChronology_(millis, chrono);
      if (iZone_ != nil) {
        dt = [dt withZoneWithOrgJodaTimeDateTimeZone:iZone_];
      }
      return dt;
    }
  }
  else {
    newPos = ~newPos;
  }
  @throw new_JavaLangIllegalArgumentException_initWithNSString_(OrgJodaTimeFormatFormatUtils_createErrorMessageWithNSString_withInt_(text, newPos));
}

- (OrgJodaTimeMutableDateTime *)parseMutableDateTimeWithNSString:(NSString *)text {
  id<OrgJodaTimeFormatInternalParser> parser = OrgJodaTimeFormatDateTimeFormatter_requireParser(self);
  OrgJodaTimeChronology *chrono = OrgJodaTimeFormatDateTimeFormatter_selectChronologyWithOrgJodaTimeChronology_(self, nil);
  OrgJodaTimeFormatDateTimeParserBucket *bucket = new_OrgJodaTimeFormatDateTimeParserBucket_initWithLong_withOrgJodaTimeChronology_withJavaUtilLocale_withJavaLangInteger_withInt_(0, chrono, iLocale_, iPivotYear_, iDefaultYear_);
  jint newPos = [((id<OrgJodaTimeFormatInternalParser>) nil_chk(parser)) parseIntoWithOrgJodaTimeFormatDateTimeParserBucket:bucket withJavaLangCharSequence:text withInt:0];
  if (newPos >= 0) {
    if (newPos >= ((jint) [((NSString *) nil_chk(text)) length])) {
      jlong millis = [bucket computeMillisWithBoolean:true withNSString:text];
      if (iOffsetParsed_ && [bucket getOffsetInteger] != nil) {
        jint parsedOffset = [((JavaLangInteger *) nil_chk([bucket getOffsetInteger])) intValue];
        OrgJodaTimeDateTimeZone *parsedZone = OrgJodaTimeDateTimeZone_forOffsetMillisWithInt_(parsedOffset);
        chrono = [((OrgJodaTimeChronology *) nil_chk(chrono)) withZoneWithOrgJodaTimeDateTimeZone:parsedZone];
      }
      else if ([bucket getZone] != nil) {
        chrono = [((OrgJodaTimeChronology *) nil_chk(chrono)) withZoneWithOrgJodaTimeDateTimeZone:[bucket getZone]];
      }
      OrgJodaTimeMutableDateTime *dt = new_OrgJodaTimeMutableDateTime_initWithLong_withOrgJodaTimeChronology_(millis, chrono);
      if (iZone_ != nil) {
        [dt setZoneWithOrgJodaTimeDateTimeZone:iZone_];
      }
      return dt;
    }
  }
  else {
    newPos = ~newPos;
  }
  @throw new_JavaLangIllegalArgumentException_initWithNSString_(OrgJodaTimeFormatFormatUtils_createErrorMessageWithNSString_withInt_(text, newPos));
}

- (id<OrgJodaTimeFormatInternalParser>)requireParser {
  return OrgJodaTimeFormatDateTimeFormatter_requireParser(self);
}

- (OrgJodaTimeChronology *)selectChronologyWithOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono {
  return OrgJodaTimeFormatDateTimeFormatter_selectChronologyWithOrgJodaTimeChronology_(self, chrono);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, 2, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimePrinter;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatInternalPrinter;", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimeParser;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatInternalParser;", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimeFormatter;", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LJavaUtilLocale;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimeFormatter;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimeFormatter;", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeChronology;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeChronology;", 0x1, -1, -1, -1, -1, 7, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimeFormatter;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimeFormatter;", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeDateTimeZone;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimeFormatter;", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimeFormatter;", 0x1, 10, 12, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatDateTimeFormatter;", 0x1, 13, 12, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 15, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 16, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 17, 18, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 19, 18, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 20, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 22, 18, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 23, 18, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 24, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 26, 18, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 27, 18, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 28, 29, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 28, 30, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 28, 31, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 14, 32, 18, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatInternalPrinter;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 33, 34, -1, -1, -1, -1 },
    { NULL, "J", 0x1, 35, 36, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeLocalDate;", 0x1, 37, 36, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeLocalTime;", 0x1, 38, 36, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeLocalDateTime;", 0x1, 39, 36, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeDateTime;", 0x1, 40, 36, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeMutableDateTime;", 0x1, 41, 36, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeFormatInternalParser;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeChronology;", 0x2, 42, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgJodaTimeFormatDateTimePrinter:withOrgJodaTimeFormatDateTimeParser:);
  methods[1].selector = @selector(initWithOrgJodaTimeFormatInternalPrinter:withOrgJodaTimeFormatInternalParser:);
  methods[2].selector = @selector(initWithOrgJodaTimeFormatInternalPrinter:withOrgJodaTimeFormatInternalParser:withJavaUtilLocale:withBoolean:withOrgJodaTimeChronology:withOrgJodaTimeDateTimeZone:withJavaLangInteger:withInt:);
  methods[3].selector = @selector(isPrinter);
  methods[4].selector = @selector(getPrinter);
  methods[5].selector = @selector(getPrinter0);
  methods[6].selector = @selector(isParser);
  methods[7].selector = @selector(getParser);
  methods[8].selector = @selector(getParser0);
  methods[9].selector = @selector(withLocaleWithJavaUtilLocale:);
  methods[10].selector = @selector(getLocale);
  methods[11].selector = @selector(withOffsetParsed);
  methods[12].selector = @selector(isOffsetParsed);
  methods[13].selector = @selector(withChronologyWithOrgJodaTimeChronology:);
  methods[14].selector = @selector(getChronology);
  methods[15].selector = @selector(getChronolgy);
  methods[16].selector = @selector(withZoneUTC);
  methods[17].selector = @selector(withZoneWithOrgJodaTimeDateTimeZone:);
  methods[18].selector = @selector(getZone);
  methods[19].selector = @selector(withPivotYearWithJavaLangInteger:);
  methods[20].selector = @selector(withPivotYearWithInt:);
  methods[21].selector = @selector(getPivotYear);
  methods[22].selector = @selector(withDefaultYearWithInt:);
  methods[23].selector = @selector(getDefaultYear);
  methods[24].selector = @selector(printToWithJavaLangStringBuffer:withOrgJodaTimeReadableInstant:);
  methods[25].selector = @selector(printToWithJavaLangStringBuilder:withOrgJodaTimeReadableInstant:);
  methods[26].selector = @selector(printToWithJavaIoWriter:withOrgJodaTimeReadableInstant:);
  methods[27].selector = @selector(printToWithJavaLangAppendable:withOrgJodaTimeReadableInstant:);
  methods[28].selector = @selector(printToWithJavaLangStringBuffer:withLong:);
  methods[29].selector = @selector(printToWithJavaLangStringBuilder:withLong:);
  methods[30].selector = @selector(printToWithJavaIoWriter:withLong:);
  methods[31].selector = @selector(printToWithJavaLangAppendable:withLong:);
  methods[32].selector = @selector(printToWithJavaLangStringBuffer:withOrgJodaTimeReadablePartial:);
  methods[33].selector = @selector(printToWithJavaLangStringBuilder:withOrgJodaTimeReadablePartial:);
  methods[34].selector = @selector(printToWithJavaIoWriter:withOrgJodaTimeReadablePartial:);
  methods[35].selector = @selector(printToWithJavaLangAppendable:withOrgJodaTimeReadablePartial:);
  methods[36].selector = @selector(printWithOrgJodaTimeReadableInstant:);
  methods[37].selector = @selector(printWithLong:);
  methods[38].selector = @selector(printWithOrgJodaTimeReadablePartial:);
  methods[39].selector = @selector(printToWithJavaLangAppendable:withLong:withOrgJodaTimeChronology:);
  methods[40].selector = @selector(requirePrinter);
  methods[41].selector = @selector(parseIntoWithOrgJodaTimeReadWritableInstant:withNSString:withInt:);
  methods[42].selector = @selector(parseMillisWithNSString:);
  methods[43].selector = @selector(parseLocalDateWithNSString:);
  methods[44].selector = @selector(parseLocalTimeWithNSString:);
  methods[45].selector = @selector(parseLocalDateTimeWithNSString:);
  methods[46].selector = @selector(parseDateTimeWithNSString:);
  methods[47].selector = @selector(parseMutableDateTimeWithNSString:);
  methods[48].selector = @selector(requireParser);
  methods[49].selector = @selector(selectChronologyWithOrgJodaTimeChronology:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "iPrinter_", "LOrgJodaTimeFormatInternalPrinter;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "iParser_", "LOrgJodaTimeFormatInternalParser;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "iLocale_", "LJavaUtilLocale;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "iOffsetParsed_", "Z", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "iChrono_", "LOrgJodaTimeChronology;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "iZone_", "LOrgJodaTimeDateTimeZone;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "iPivotYear_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "iDefaultYear_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgJodaTimeFormatDateTimePrinter;LOrgJodaTimeFormatDateTimeParser;", "LOrgJodaTimeFormatInternalPrinter;LOrgJodaTimeFormatInternalParser;", "LOrgJodaTimeFormatInternalPrinter;LOrgJodaTimeFormatInternalParser;LJavaUtilLocale;ZLOrgJodaTimeChronology;LOrgJodaTimeDateTimeZone;LJavaLangInteger;I", "withLocale", "LJavaUtilLocale;", "withChronology", "LOrgJodaTimeChronology;", (void *)&OrgJodaTimeFormatDateTimeFormatter__Annotations$0, "withZone", "LOrgJodaTimeDateTimeZone;", "withPivotYear", "LJavaLangInteger;", "I", "withDefaultYear", "printTo", "LJavaLangStringBuffer;LOrgJodaTimeReadableInstant;", "LJavaLangStringBuilder;LOrgJodaTimeReadableInstant;", "LJavaIoWriter;LOrgJodaTimeReadableInstant;", "LJavaIoIOException;", "LJavaLangAppendable;LOrgJodaTimeReadableInstant;", "LJavaLangStringBuffer;J", "LJavaLangStringBuilder;J", "LJavaIoWriter;J", "LJavaLangAppendable;J", "LJavaLangStringBuffer;LOrgJodaTimeReadablePartial;", "LJavaLangStringBuilder;LOrgJodaTimeReadablePartial;", "LJavaIoWriter;LOrgJodaTimeReadablePartial;", "LJavaLangAppendable;LOrgJodaTimeReadablePartial;", "print", "LOrgJodaTimeReadableInstant;", "J", "LOrgJodaTimeReadablePartial;", "LJavaLangAppendable;JLOrgJodaTimeChronology;", "parseInto", "LOrgJodaTimeReadWritableInstant;LNSString;I", "parseMillis", "LNSString;", "parseLocalDate", "parseLocalTime", "parseLocalDateTime", "parseDateTime", "parseMutableDateTime", "selectChronology" };
  static const J2ObjcClassInfo _OrgJodaTimeFormatDateTimeFormatter = { "DateTimeFormatter", "org.joda.time.format", ptrTable, methods, fields, 7, 0x1, 50, 8, -1, -1, -1, -1, -1 };
  return &_OrgJodaTimeFormatDateTimeFormatter;
}

@end

void OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatDateTimePrinter_withOrgJodaTimeFormatDateTimeParser_(OrgJodaTimeFormatDateTimeFormatter *self, id<OrgJodaTimeFormatDateTimePrinter> printer, id<OrgJodaTimeFormatDateTimeParser> parser) {
  OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_(self, OrgJodaTimeFormatDateTimePrinterInternalPrinter_ofWithOrgJodaTimeFormatDateTimePrinter_(printer), OrgJodaTimeFormatDateTimeParserInternalParser_ofWithOrgJodaTimeFormatDateTimeParser_(parser));
}

OrgJodaTimeFormatDateTimeFormatter *new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatDateTimePrinter_withOrgJodaTimeFormatDateTimeParser_(id<OrgJodaTimeFormatDateTimePrinter> printer, id<OrgJodaTimeFormatDateTimeParser> parser) {
  J2OBJC_NEW_IMPL(OrgJodaTimeFormatDateTimeFormatter, initWithOrgJodaTimeFormatDateTimePrinter_withOrgJodaTimeFormatDateTimeParser_, printer, parser)
}

OrgJodaTimeFormatDateTimeFormatter *create_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatDateTimePrinter_withOrgJodaTimeFormatDateTimeParser_(id<OrgJodaTimeFormatDateTimePrinter> printer, id<OrgJodaTimeFormatDateTimeParser> parser) {
  J2OBJC_CREATE_IMPL(OrgJodaTimeFormatDateTimeFormatter, initWithOrgJodaTimeFormatDateTimePrinter_withOrgJodaTimeFormatDateTimeParser_, printer, parser)
}

void OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_(OrgJodaTimeFormatDateTimeFormatter *self, id<OrgJodaTimeFormatInternalPrinter> printer, id<OrgJodaTimeFormatInternalParser> parser) {
  NSObject_init(self);
  self->iPrinter_ = printer;
  self->iParser_ = parser;
  self->iLocale_ = nil;
  self->iOffsetParsed_ = false;
  self->iChrono_ = nil;
  self->iZone_ = nil;
  self->iPivotYear_ = nil;
  self->iDefaultYear_ = 2000;
}

OrgJodaTimeFormatDateTimeFormatter *new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_(id<OrgJodaTimeFormatInternalPrinter> printer, id<OrgJodaTimeFormatInternalParser> parser) {
  J2OBJC_NEW_IMPL(OrgJodaTimeFormatDateTimeFormatter, initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_, printer, parser)
}

OrgJodaTimeFormatDateTimeFormatter *create_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_(id<OrgJodaTimeFormatInternalPrinter> printer, id<OrgJodaTimeFormatInternalParser> parser) {
  J2OBJC_CREATE_IMPL(OrgJodaTimeFormatDateTimeFormatter, initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_, printer, parser)
}

void OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(OrgJodaTimeFormatDateTimeFormatter *self, id<OrgJodaTimeFormatInternalPrinter> printer, id<OrgJodaTimeFormatInternalParser> parser, JavaUtilLocale *locale, jboolean offsetParsed, OrgJodaTimeChronology *chrono, OrgJodaTimeDateTimeZone *zone, JavaLangInteger *pivotYear, jint defaultYear) {
  NSObject_init(self);
  self->iPrinter_ = printer;
  self->iParser_ = parser;
  self->iLocale_ = locale;
  self->iOffsetParsed_ = offsetParsed;
  self->iChrono_ = chrono;
  self->iZone_ = zone;
  self->iPivotYear_ = pivotYear;
  self->iDefaultYear_ = defaultYear;
}

OrgJodaTimeFormatDateTimeFormatter *new_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(id<OrgJodaTimeFormatInternalPrinter> printer, id<OrgJodaTimeFormatInternalParser> parser, JavaUtilLocale *locale, jboolean offsetParsed, OrgJodaTimeChronology *chrono, OrgJodaTimeDateTimeZone *zone, JavaLangInteger *pivotYear, jint defaultYear) {
  J2OBJC_NEW_IMPL(OrgJodaTimeFormatDateTimeFormatter, initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_, printer, parser, locale, offsetParsed, chrono, zone, pivotYear, defaultYear)
}

OrgJodaTimeFormatDateTimeFormatter *create_OrgJodaTimeFormatDateTimeFormatter_initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_(id<OrgJodaTimeFormatInternalPrinter> printer, id<OrgJodaTimeFormatInternalParser> parser, JavaUtilLocale *locale, jboolean offsetParsed, OrgJodaTimeChronology *chrono, OrgJodaTimeDateTimeZone *zone, JavaLangInteger *pivotYear, jint defaultYear) {
  J2OBJC_CREATE_IMPL(OrgJodaTimeFormatDateTimeFormatter, initWithOrgJodaTimeFormatInternalPrinter_withOrgJodaTimeFormatInternalParser_withJavaUtilLocale_withBoolean_withOrgJodaTimeChronology_withOrgJodaTimeDateTimeZone_withJavaLangInteger_withInt_, printer, parser, locale, offsetParsed, chrono, zone, pivotYear, defaultYear)
}

void OrgJodaTimeFormatDateTimeFormatter_printToWithJavaLangAppendable_withLong_withOrgJodaTimeChronology_(OrgJodaTimeFormatDateTimeFormatter *self, id<JavaLangAppendable> appendable, jlong instant, OrgJodaTimeChronology *chrono) {
  id<OrgJodaTimeFormatInternalPrinter> printer = OrgJodaTimeFormatDateTimeFormatter_requirePrinter(self);
  chrono = OrgJodaTimeFormatDateTimeFormatter_selectChronologyWithOrgJodaTimeChronology_(self, chrono);
  OrgJodaTimeDateTimeZone *zone = [((OrgJodaTimeChronology *) nil_chk(chrono)) getZone];
  jint offset = [((OrgJodaTimeDateTimeZone *) nil_chk(zone)) getOffsetWithLong:instant];
  jlong adjustedInstant = instant + offset;
  if ((instant ^ adjustedInstant) < 0 && (instant ^ offset) >= 0) {
    zone = JreLoadStatic(OrgJodaTimeDateTimeZone, UTC);
    offset = 0;
    adjustedInstant = instant;
  }
  [((id<OrgJodaTimeFormatInternalPrinter>) nil_chk(printer)) printToWithJavaLangAppendable:appendable withLong:adjustedInstant withOrgJodaTimeChronology:[chrono withUTC] withInt:offset withOrgJodaTimeDateTimeZone:zone withJavaUtilLocale:self->iLocale_];
}

id<OrgJodaTimeFormatInternalPrinter> OrgJodaTimeFormatDateTimeFormatter_requirePrinter(OrgJodaTimeFormatDateTimeFormatter *self) {
  id<OrgJodaTimeFormatInternalPrinter> printer = self->iPrinter_;
  if (printer == nil) {
    @throw new_JavaLangUnsupportedOperationException_initWithNSString_(@"Printing not supported");
  }
  return printer;
}

id<OrgJodaTimeFormatInternalParser> OrgJodaTimeFormatDateTimeFormatter_requireParser(OrgJodaTimeFormatDateTimeFormatter *self) {
  id<OrgJodaTimeFormatInternalParser> parser = self->iParser_;
  if (parser == nil) {
    @throw new_JavaLangUnsupportedOperationException_initWithNSString_(@"Parsing not supported");
  }
  return parser;
}

OrgJodaTimeChronology *OrgJodaTimeFormatDateTimeFormatter_selectChronologyWithOrgJodaTimeChronology_(OrgJodaTimeFormatDateTimeFormatter *self, OrgJodaTimeChronology *chrono) {
  chrono = OrgJodaTimeDateTimeUtils_getChronologyWithOrgJodaTimeChronology_(chrono);
  if (self->iChrono_ != nil) {
    chrono = self->iChrono_;
  }
  if (self->iZone_ != nil) {
    chrono = [((OrgJodaTimeChronology *) nil_chk(chrono)) withZoneWithOrgJodaTimeDateTimeZone:self->iZone_];
  }
  return chrono;
}

IOSObjectArray *OrgJodaTimeFormatDateTimeFormatter__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgJodaTimeFormatDateTimeFormatter)
