//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/field/DelegatedDurationField.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DelegatedDurationField")
#ifdef RESTRICT_DelegatedDurationField
#define INCLUDE_ALL_DelegatedDurationField 0
#else
#define INCLUDE_ALL_DelegatedDurationField 1
#endif
#undef RESTRICT_DelegatedDurationField

#if !defined (OrgJodaTimeFieldDelegatedDurationField_) && (INCLUDE_ALL_DelegatedDurationField || defined(INCLUDE_OrgJodaTimeFieldDelegatedDurationField))
#define OrgJodaTimeFieldDelegatedDurationField_

#define RESTRICT_DurationField 1
#define INCLUDE_OrgJodaTimeDurationField 1
#include "DurationField.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class OrgJodaTimeDurationFieldType;

@interface OrgJodaTimeFieldDelegatedDurationField : OrgJodaTimeDurationField < JavaIoSerializable >

#pragma mark Public

- (jlong)addWithLong:(jlong)instant
             withInt:(jint)value;

- (jlong)addWithLong:(jlong)instant
            withLong:(jlong)value;

- (jint)compareToWithId:(OrgJodaTimeDurationField *)durationField;

- (jboolean)isEqual:(id)obj;

- (jint)getDifferenceWithLong:(jlong)minuendInstant
                     withLong:(jlong)subtrahendInstant;

- (jlong)getDifferenceAsLongWithLong:(jlong)minuendInstant
                            withLong:(jlong)subtrahendInstant;

- (jlong)getMillisWithInt:(jint)value;

- (jlong)getMillisWithInt:(jint)value
                 withLong:(jlong)instant;

- (jlong)getMillisWithLong:(jlong)value;

- (jlong)getMillisWithLong:(jlong)value
                  withLong:(jlong)instant;

- (NSString *)getName;

- (OrgJodaTimeDurationFieldType *)getType;

- (jlong)getUnitMillis;

- (jint)getValueWithLong:(jlong)duration;

- (jint)getValueWithLong:(jlong)duration
                withLong:(jlong)instant;

- (jlong)getValueAsLongWithLong:(jlong)duration;

- (jlong)getValueAsLongWithLong:(jlong)duration
                       withLong:(jlong)instant;

- (OrgJodaTimeDurationField *)getWrappedField;

- (NSUInteger)hash;

- (jboolean)isPrecise;

- (jboolean)isSupported;

- (NSString *)description;

#pragma mark Protected

- (instancetype)initWithOrgJodaTimeDurationField:(OrgJodaTimeDurationField *)field;

- (instancetype)initWithOrgJodaTimeDurationField:(OrgJodaTimeDurationField *)field
                withOrgJodaTimeDurationFieldType:(OrgJodaTimeDurationFieldType *)type;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeFieldDelegatedDurationField)

FOUNDATION_EXPORT void OrgJodaTimeFieldDelegatedDurationField_initWithOrgJodaTimeDurationField_(OrgJodaTimeFieldDelegatedDurationField *self, OrgJodaTimeDurationField *field);

FOUNDATION_EXPORT OrgJodaTimeFieldDelegatedDurationField *new_OrgJodaTimeFieldDelegatedDurationField_initWithOrgJodaTimeDurationField_(OrgJodaTimeDurationField *field) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeFieldDelegatedDurationField *create_OrgJodaTimeFieldDelegatedDurationField_initWithOrgJodaTimeDurationField_(OrgJodaTimeDurationField *field);

FOUNDATION_EXPORT void OrgJodaTimeFieldDelegatedDurationField_initWithOrgJodaTimeDurationField_withOrgJodaTimeDurationFieldType_(OrgJodaTimeFieldDelegatedDurationField *self, OrgJodaTimeDurationField *field, OrgJodaTimeDurationFieldType *type);

FOUNDATION_EXPORT OrgJodaTimeFieldDelegatedDurationField *new_OrgJodaTimeFieldDelegatedDurationField_initWithOrgJodaTimeDurationField_withOrgJodaTimeDurationFieldType_(OrgJodaTimeDurationField *field, OrgJodaTimeDurationFieldType *type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeFieldDelegatedDurationField *create_OrgJodaTimeFieldDelegatedDurationField_initWithOrgJodaTimeDurationField_withOrgJodaTimeDurationFieldType_(OrgJodaTimeDurationField *field, OrgJodaTimeDurationFieldType *type);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeFieldDelegatedDurationField)

#endif

#pragma pop_macro("INCLUDE_ALL_DelegatedDurationField")
