//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/convert/DurationConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DurationConverter")
#ifdef RESTRICT_DurationConverter
#define INCLUDE_ALL_DurationConverter 0
#else
#define INCLUDE_ALL_DurationConverter 1
#endif
#undef RESTRICT_DurationConverter

#if !defined (OrgJodaTimeConvertDurationConverter_) && (INCLUDE_ALL_DurationConverter || defined(INCLUDE_OrgJodaTimeConvertDurationConverter))
#define OrgJodaTimeConvertDurationConverter_

#define RESTRICT_Converter 1
#define INCLUDE_OrgJodaTimeConvertConverter 1
#include "Converter.h"

@protocol OrgJodaTimeConvertDurationConverter < OrgJodaTimeConvertConverter, JavaObject >

- (jlong)getDurationMillisWithId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeConvertDurationConverter)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeConvertDurationConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_DurationConverter")
