//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/chrono/GJCacheKey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_GJCacheKey")
#ifdef RESTRICT_GJCacheKey
#define INCLUDE_ALL_GJCacheKey 0
#else
#define INCLUDE_ALL_GJCacheKey 1
#endif
#undef RESTRICT_GJCacheKey

#if !defined (OrgJodaTimeChronoGJCacheKey_) && (INCLUDE_ALL_GJCacheKey || defined(INCLUDE_OrgJodaTimeChronoGJCacheKey))
#define OrgJodaTimeChronoGJCacheKey_

@class OrgJodaTimeDateTimeZone;
@class OrgJodaTimeInstant;

@interface OrgJodaTimeChronoGJCacheKey : NSObject

#pragma mark Public

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

#pragma mark Package-Private

- (instancetype)initWithOrgJodaTimeDateTimeZone:(OrgJodaTimeDateTimeZone *)zone
                         withOrgJodaTimeInstant:(OrgJodaTimeInstant *)cutoverInstant
                                        withInt:(jint)minDaysInFirstWeek;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeChronoGJCacheKey)

FOUNDATION_EXPORT void OrgJodaTimeChronoGJCacheKey_initWithOrgJodaTimeDateTimeZone_withOrgJodaTimeInstant_withInt_(OrgJodaTimeChronoGJCacheKey *self, OrgJodaTimeDateTimeZone *zone, OrgJodaTimeInstant *cutoverInstant, jint minDaysInFirstWeek);

FOUNDATION_EXPORT OrgJodaTimeChronoGJCacheKey *new_OrgJodaTimeChronoGJCacheKey_initWithOrgJodaTimeDateTimeZone_withOrgJodaTimeInstant_withInt_(OrgJodaTimeDateTimeZone *zone, OrgJodaTimeInstant *cutoverInstant, jint minDaysInFirstWeek) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeChronoGJCacheKey *create_OrgJodaTimeChronoGJCacheKey_initWithOrgJodaTimeDateTimeZone_withOrgJodaTimeInstant_withInt_(OrgJodaTimeDateTimeZone *zone, OrgJodaTimeInstant *cutoverInstant, jint minDaysInFirstWeek);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeChronoGJCacheKey)

#endif

#pragma pop_macro("INCLUDE_ALL_GJCacheKey")
