//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/format/InternalPrinter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_InternalPrinter")
#ifdef RESTRICT_InternalPrinter
#define INCLUDE_ALL_InternalPrinter 0
#else
#define INCLUDE_ALL_InternalPrinter 1
#endif
#undef RESTRICT_InternalPrinter

#if !defined (OrgJodaTimeFormatInternalPrinter_) && (INCLUDE_ALL_InternalPrinter || defined(INCLUDE_OrgJodaTimeFormatInternalPrinter))
#define OrgJodaTimeFormatInternalPrinter_

@class JavaUtilLocale;
@class OrgJodaTimeChronology;
@class OrgJodaTimeDateTimeZone;
@protocol JavaLangAppendable;
@protocol OrgJodaTimeReadablePartial;

@protocol OrgJodaTimeFormatInternalPrinter < JavaObject >

- (jint)estimatePrintedLength;

- (void)printToWithJavaLangAppendable:(id<JavaLangAppendable>)appendable
                             withLong:(jlong)instant
            withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono
                              withInt:(jint)displayOffset
          withOrgJodaTimeDateTimeZone:(OrgJodaTimeDateTimeZone *)displayZone
                   withJavaUtilLocale:(JavaUtilLocale *)locale;

- (void)printToWithJavaLangAppendable:(id<JavaLangAppendable>)appendable
       withOrgJodaTimeReadablePartial:(id<OrgJodaTimeReadablePartial>)partial
                   withJavaUtilLocale:(JavaUtilLocale *)locale;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeFormatInternalPrinter)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeFormatInternalPrinter)

#endif

#pragma pop_macro("INCLUDE_ALL_InternalPrinter")
