//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/JodaTimePermission.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JodaTimePermission")
#ifdef RESTRICT_JodaTimePermission
#define INCLUDE_ALL_JodaTimePermission 0
#else
#define INCLUDE_ALL_JodaTimePermission 1
#endif
#undef RESTRICT_JodaTimePermission

#if !defined (OrgJodaTimeJodaTimePermission_) && (INCLUDE_ALL_JodaTimePermission || defined(INCLUDE_OrgJodaTimeJodaTimePermission))
#define OrgJodaTimeJodaTimePermission_

#define RESTRICT_JavaSecurityBasicPermission 1
#define INCLUDE_JavaSecurityBasicPermission 1
#include "java/security/BasicPermission.h"

@interface OrgJodaTimeJodaTimePermission : JavaSecurityBasicPermission

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)name;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeJodaTimePermission)

FOUNDATION_EXPORT void OrgJodaTimeJodaTimePermission_initWithNSString_(OrgJodaTimeJodaTimePermission *self, NSString *name);

FOUNDATION_EXPORT OrgJodaTimeJodaTimePermission *new_OrgJodaTimeJodaTimePermission_initWithNSString_(NSString *name) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeJodaTimePermission *create_OrgJodaTimeJodaTimePermission_initWithNSString_(NSString *name);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeJodaTimePermission)

#endif

#pragma pop_macro("INCLUDE_ALL_JodaTimePermission")
