//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/convert/LongConverter.java
//

#include "AbstractConverter.h"
#include "Chronology.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "LongConverter.h"
#include "java/lang/Long.h"

J2OBJC_INITIALIZED_DEFN(OrgJodaTimeConvertLongConverter)

OrgJodaTimeConvertLongConverter *OrgJodaTimeConvertLongConverter_INSTANCE;

@implementation OrgJodaTimeConvertLongConverter

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgJodaTimeConvertLongConverter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jlong)getInstantMillisWithId:(id)object
      withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono {
  return [((JavaLangLong *) nil_chk(((JavaLangLong *) cast_chk(object, [JavaLangLong class])))) longLongValue];
}

- (jlong)getDurationMillisWithId:(id)object {
  return [((JavaLangLong *) nil_chk(((JavaLangLong *) cast_chk(object, [JavaLangLong class])))) longLongValue];
}

- (IOSClass *)getSupportedType {
  return JavaLangLong_class_();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "J", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "J", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, 4, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getInstantMillisWithId:withOrgJodaTimeChronology:);
  methods[2].selector = @selector(getDurationMillisWithId:);
  methods[3].selector = @selector(getSupportedType);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "INSTANCE", "LOrgJodaTimeConvertLongConverter;", .constantValue.asLong = 0, 0x18, -1, 5, -1, -1 },
  };
  static const void *ptrTable[] = { "getInstantMillis", "LNSObject;LOrgJodaTimeChronology;", "getDurationMillis", "LNSObject;", "()Ljava/lang/Class<*>;", &OrgJodaTimeConvertLongConverter_INSTANCE };
  static const J2ObjcClassInfo _OrgJodaTimeConvertLongConverter = { "LongConverter", "org.joda.time.convert", ptrTable, methods, fields, 7, 0x0, 4, 1, -1, -1, -1, -1, -1 };
  return &_OrgJodaTimeConvertLongConverter;
}

+ (void)initialize {
  if (self == [OrgJodaTimeConvertLongConverter class]) {
    OrgJodaTimeConvertLongConverter_INSTANCE = new_OrgJodaTimeConvertLongConverter_init();
    J2OBJC_SET_INITIALIZED(OrgJodaTimeConvertLongConverter)
  }
}

@end

void OrgJodaTimeConvertLongConverter_init(OrgJodaTimeConvertLongConverter *self) {
  OrgJodaTimeConvertAbstractConverter_init(self);
}

OrgJodaTimeConvertLongConverter *new_OrgJodaTimeConvertLongConverter_init() {
  J2OBJC_NEW_IMPL(OrgJodaTimeConvertLongConverter, init)
}

OrgJodaTimeConvertLongConverter *create_OrgJodaTimeConvertLongConverter_init() {
  J2OBJC_CREATE_IMPL(OrgJodaTimeConvertLongConverter, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgJodaTimeConvertLongConverter)
