//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/convert/ReadableIntervalConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ReadableIntervalConverter")
#ifdef RESTRICT_ReadableIntervalConverter
#define INCLUDE_ALL_ReadableIntervalConverter 0
#else
#define INCLUDE_ALL_ReadableIntervalConverter 1
#endif
#undef RESTRICT_ReadableIntervalConverter

#if !defined (OrgJodaTimeConvertReadableIntervalConverter_) && (INCLUDE_ALL_ReadableIntervalConverter || defined(INCLUDE_OrgJodaTimeConvertReadableIntervalConverter))
#define OrgJodaTimeConvertReadableIntervalConverter_

#define RESTRICT_AbstractConverter 1
#define INCLUDE_OrgJodaTimeConvertAbstractConverter 1
#include "AbstractConverter.h"

#define RESTRICT_IntervalConverter 1
#define INCLUDE_OrgJodaTimeConvertIntervalConverter 1
#include "IntervalConverter.h"

#define RESTRICT_DurationConverter 1
#define INCLUDE_OrgJodaTimeConvertDurationConverter 1
#include "DurationConverter.h"

#define RESTRICT_PeriodConverter 1
#define INCLUDE_OrgJodaTimeConvertPeriodConverter 1
#include "PeriodConverter.h"

@class IOSClass;
@class OrgJodaTimeChronology;
@protocol OrgJodaTimeReadWritableInterval;
@protocol OrgJodaTimeReadWritablePeriod;

@interface OrgJodaTimeConvertReadableIntervalConverter : OrgJodaTimeConvertAbstractConverter < OrgJodaTimeConvertIntervalConverter, OrgJodaTimeConvertDurationConverter, OrgJodaTimeConvertPeriodConverter >

#pragma mark Public

- (jlong)getDurationMillisWithId:(id)object;

- (IOSClass *)getSupportedType;

- (jboolean)isReadableIntervalWithId:(id)object
           withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

- (void)setIntoWithOrgJodaTimeReadWritableInterval:(id<OrgJodaTimeReadWritableInterval>)writableInterval
                                            withId:(id)object
                         withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

- (void)setIntoWithOrgJodaTimeReadWritablePeriod:(id<OrgJodaTimeReadWritablePeriod>)writablePeriod
                                          withId:(id)object
                       withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(OrgJodaTimeConvertReadableIntervalConverter)

inline OrgJodaTimeConvertReadableIntervalConverter *OrgJodaTimeConvertReadableIntervalConverter_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJodaTimeConvertReadableIntervalConverter *OrgJodaTimeConvertReadableIntervalConverter_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJodaTimeConvertReadableIntervalConverter, INSTANCE, OrgJodaTimeConvertReadableIntervalConverter *)

FOUNDATION_EXPORT void OrgJodaTimeConvertReadableIntervalConverter_init(OrgJodaTimeConvertReadableIntervalConverter *self);

FOUNDATION_EXPORT OrgJodaTimeConvertReadableIntervalConverter *new_OrgJodaTimeConvertReadableIntervalConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeConvertReadableIntervalConverter *create_OrgJodaTimeConvertReadableIntervalConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeConvertReadableIntervalConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_ReadableIntervalConverter")
