//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/convert/ReadablePartialConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ReadablePartialConverter")
#ifdef RESTRICT_ReadablePartialConverter
#define INCLUDE_ALL_ReadablePartialConverter 0
#else
#define INCLUDE_ALL_ReadablePartialConverter 1
#endif
#undef RESTRICT_ReadablePartialConverter

#if !defined (OrgJodaTimeConvertReadablePartialConverter_) && (INCLUDE_ALL_ReadablePartialConverter || defined(INCLUDE_OrgJodaTimeConvertReadablePartialConverter))
#define OrgJodaTimeConvertReadablePartialConverter_

#define RESTRICT_AbstractConverter 1
#define INCLUDE_OrgJodaTimeConvertAbstractConverter 1
#include "AbstractConverter.h"

#define RESTRICT_PartialConverter 1
#define INCLUDE_OrgJodaTimeConvertPartialConverter 1
#include "PartialConverter.h"

@class IOSClass;
@class IOSIntArray;
@class OrgJodaTimeChronology;
@class OrgJodaTimeDateTimeZone;
@protocol OrgJodaTimeReadablePartial;

@interface OrgJodaTimeConvertReadablePartialConverter : OrgJodaTimeConvertAbstractConverter < OrgJodaTimeConvertPartialConverter >

#pragma mark Public

- (OrgJodaTimeChronology *)getChronologyWithId:(id)object
                     withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

- (OrgJodaTimeChronology *)getChronologyWithId:(id)object
                   withOrgJodaTimeDateTimeZone:(OrgJodaTimeDateTimeZone *)zone;

- (IOSIntArray *)getPartialValuesWithOrgJodaTimeReadablePartial:(id<OrgJodaTimeReadablePartial>)fieldSource
                                                         withId:(id)object
                                      withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

- (IOSClass *)getSupportedType;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(OrgJodaTimeConvertReadablePartialConverter)

inline OrgJodaTimeConvertReadablePartialConverter *OrgJodaTimeConvertReadablePartialConverter_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJodaTimeConvertReadablePartialConverter *OrgJodaTimeConvertReadablePartialConverter_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJodaTimeConvertReadablePartialConverter, INSTANCE, OrgJodaTimeConvertReadablePartialConverter *)

FOUNDATION_EXPORT void OrgJodaTimeConvertReadablePartialConverter_init(OrgJodaTimeConvertReadablePartialConverter *self);

FOUNDATION_EXPORT OrgJodaTimeConvertReadablePartialConverter *new_OrgJodaTimeConvertReadablePartialConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeConvertReadablePartialConverter *create_OrgJodaTimeConvertReadablePartialConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeConvertReadablePartialConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_ReadablePartialConverter")
