//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/ReadableInstant.java
//

#include "J2ObjC_source.h"
#include "ReadableInstant.h"

@interface OrgJodaTimeReadableInstant : NSObject

@end

@implementation OrgJodaTimeReadableInstant

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "J", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeChronology;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeDateTimeZone;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 2, 1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeInstant;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 3, 4, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 5, 4, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 6, 4, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 7, 8, -1, -1, -1, -1 },
    { NULL, "I", 0x401, 9, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 10, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getMillis);
  methods[1].selector = @selector(getChronology);
  methods[2].selector = @selector(getZone);
  methods[3].selector = @selector(getWithOrgJodaTimeDateTimeFieldType:);
  methods[4].selector = @selector(isSupportedWithOrgJodaTimeDateTimeFieldType:);
  methods[5].selector = @selector(toInstant);
  methods[6].selector = @selector(isEqualWithOrgJodaTimeReadableInstant:);
  methods[7].selector = @selector(isAfterWithOrgJodaTimeReadableInstant:);
  methods[8].selector = @selector(isBeforeWithOrgJodaTimeReadableInstant:);
  methods[9].selector = @selector(isEqual:);
  methods[10].selector = @selector(hash);
  methods[11].selector = @selector(description);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "get", "LOrgJodaTimeDateTimeFieldType;", "isSupported", "isEqual", "LOrgJodaTimeReadableInstant;", "isAfter", "isBefore", "equals", "LNSObject;", "hashCode", "toString", "Ljava/lang/Object;Ljava/lang/Comparable<Lorg/joda/time/ReadableInstant;>;" };
  static const J2ObjcClassInfo _OrgJodaTimeReadableInstant = { "ReadableInstant", "org.joda.time", ptrTable, methods, NULL, 7, 0x609, 12, 0, -1, -1, -1, 11, -1 };
  return &_OrgJodaTimeReadableInstant;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJodaTimeReadableInstant)
