//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/ReadWritablePeriod.java
//

#include "J2ObjC_source.h"
#include "ReadWritablePeriod.h"

@interface OrgJodaTimeReadWritablePeriod : NSObject

@end

@implementation OrgJodaTimeReadWritablePeriod

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 8, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 8, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 8, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 8, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 9, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 11, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 12, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 13, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 14, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 15, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 16, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 17, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 18, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 19, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 20, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 21, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 22, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 23, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 24, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 25, 10, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(clear);
  methods[1].selector = @selector(setValueWithInt:withInt:);
  methods[2].selector = @selector(setWithOrgJodaTimeDurationFieldType:withInt:);
  methods[3].selector = @selector(setPeriodWithOrgJodaTimeReadablePeriod:);
  methods[4].selector = @selector(setPeriodWithInt:withInt:withInt:withInt:withInt:withInt:withInt:withInt:);
  methods[5].selector = @selector(setPeriodWithOrgJodaTimeReadableInterval:);
  methods[6].selector = @selector(addWithOrgJodaTimeDurationFieldType:withInt:);
  methods[7].selector = @selector(addWithOrgJodaTimeReadablePeriod:);
  methods[8].selector = @selector(addWithInt:withInt:withInt:withInt:withInt:withInt:withInt:withInt:);
  methods[9].selector = @selector(addWithOrgJodaTimeReadableInterval:);
  methods[10].selector = @selector(setYearsWithInt:);
  methods[11].selector = @selector(addYearsWithInt:);
  methods[12].selector = @selector(setMonthsWithInt:);
  methods[13].selector = @selector(addMonthsWithInt:);
  methods[14].selector = @selector(setWeeksWithInt:);
  methods[15].selector = @selector(addWeeksWithInt:);
  methods[16].selector = @selector(setDaysWithInt:);
  methods[17].selector = @selector(addDaysWithInt:);
  methods[18].selector = @selector(setHoursWithInt:);
  methods[19].selector = @selector(addHoursWithInt:);
  methods[20].selector = @selector(setMinutesWithInt:);
  methods[21].selector = @selector(addMinutesWithInt:);
  methods[22].selector = @selector(setSecondsWithInt:);
  methods[23].selector = @selector(addSecondsWithInt:);
  methods[24].selector = @selector(setMillisWithInt:);
  methods[25].selector = @selector(addMillisWithInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "setValue", "II", "set", "LOrgJodaTimeDurationFieldType;I", "setPeriod", "LOrgJodaTimeReadablePeriod;", "IIIIIIII", "LOrgJodaTimeReadableInterval;", "add", "setYears", "I", "addYears", "setMonths", "addMonths", "setWeeks", "addWeeks", "setDays", "addDays", "setHours", "addHours", "setMinutes", "addMinutes", "setSeconds", "addSeconds", "setMillis", "addMillis" };
  static const J2ObjcClassInfo _OrgJodaTimeReadWritablePeriod = { "ReadWritablePeriod", "org.joda.time", ptrTable, methods, NULL, 7, 0x609, 26, 0, -1, -1, -1, -1, -1 };
  return &_OrgJodaTimeReadWritablePeriod;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJodaTimeReadWritablePeriod)
