//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/ReadWritablePeriod.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ReadWritablePeriod")
#ifdef RESTRICT_ReadWritablePeriod
#define INCLUDE_ALL_ReadWritablePeriod 0
#else
#define INCLUDE_ALL_ReadWritablePeriod 1
#endif
#undef RESTRICT_ReadWritablePeriod

#if !defined (OrgJodaTimeReadWritablePeriod_) && (INCLUDE_ALL_ReadWritablePeriod || defined(INCLUDE_OrgJodaTimeReadWritablePeriod))
#define OrgJodaTimeReadWritablePeriod_

#define RESTRICT_ReadablePeriod 1
#define INCLUDE_OrgJodaTimeReadablePeriod 1
#include "ReadablePeriod.h"

@class OrgJodaTimeDurationFieldType;
@protocol OrgJodaTimeReadableInterval;

@protocol OrgJodaTimeReadWritablePeriod < OrgJodaTimeReadablePeriod, JavaObject >

- (void)clear;

- (void)setValueWithInt:(jint)index
                withInt:(jint)value;

- (void)setWithOrgJodaTimeDurationFieldType:(OrgJodaTimeDurationFieldType *)field
                                    withInt:(jint)value;

- (void)setPeriodWithOrgJodaTimeReadablePeriod:(id<OrgJodaTimeReadablePeriod>)period;

- (void)setPeriodWithInt:(jint)years
                 withInt:(jint)months
                 withInt:(jint)weeks
                 withInt:(jint)days
                 withInt:(jint)hours
                 withInt:(jint)minutes
                 withInt:(jint)seconds
                 withInt:(jint)millis;

- (void)setPeriodWithOrgJodaTimeReadableInterval:(id<OrgJodaTimeReadableInterval>)interval;

- (void)addWithOrgJodaTimeDurationFieldType:(OrgJodaTimeDurationFieldType *)field
                                    withInt:(jint)value;

- (void)addWithOrgJodaTimeReadablePeriod:(id<OrgJodaTimeReadablePeriod>)period;

- (void)addWithInt:(jint)years
           withInt:(jint)months
           withInt:(jint)weeks
           withInt:(jint)days
           withInt:(jint)hours
           withInt:(jint)minutes
           withInt:(jint)seconds
           withInt:(jint)millis;

- (void)addWithOrgJodaTimeReadableInterval:(id<OrgJodaTimeReadableInterval>)interval;

- (void)setYearsWithInt:(jint)years;

- (void)addYearsWithInt:(jint)years;

- (void)setMonthsWithInt:(jint)months;

- (void)addMonthsWithInt:(jint)months;

- (void)setWeeksWithInt:(jint)weeks;

- (void)addWeeksWithInt:(jint)weeks;

- (void)setDaysWithInt:(jint)days;

- (void)addDaysWithInt:(jint)days;

- (void)setHoursWithInt:(jint)hours;

- (void)addHoursWithInt:(jint)hours;

- (void)setMinutesWithInt:(jint)minutes;

- (void)addMinutesWithInt:(jint)minutes;

- (void)setSecondsWithInt:(jint)seconds;

- (void)addSecondsWithInt:(jint)seconds;

- (void)setMillisWithInt:(jint)millis;

- (void)addMillisWithInt:(jint)millis;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeReadWritablePeriod)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeReadWritablePeriod)

#endif

#pragma pop_macro("INCLUDE_ALL_ReadWritablePeriod")
