//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-time/build/mainTranslationExtraction/org/joda/time/field/ScaledDurationField.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ScaledDurationField")
#ifdef RESTRICT_ScaledDurationField
#define INCLUDE_ALL_ScaledDurationField 0
#else
#define INCLUDE_ALL_ScaledDurationField 1
#endif
#undef RESTRICT_ScaledDurationField

#if !defined (OrgJodaTimeFieldScaledDurationField_) && (INCLUDE_ALL_ScaledDurationField || defined(INCLUDE_OrgJodaTimeFieldScaledDurationField))
#define OrgJodaTimeFieldScaledDurationField_

#define RESTRICT_DecoratedDurationField 1
#define INCLUDE_OrgJodaTimeFieldDecoratedDurationField 1
#include "DecoratedDurationField.h"

@class OrgJodaTimeDurationField;
@class OrgJodaTimeDurationFieldType;

@interface OrgJodaTimeFieldScaledDurationField : OrgJodaTimeFieldDecoratedDurationField

#pragma mark Public

- (instancetype)initWithOrgJodaTimeDurationField:(OrgJodaTimeDurationField *)field
                withOrgJodaTimeDurationFieldType:(OrgJodaTimeDurationFieldType *)type
                                         withInt:(jint)scalar;

- (jlong)addWithLong:(jlong)instant
             withInt:(jint)value;

- (jlong)addWithLong:(jlong)instant
            withLong:(jlong)value;

- (jboolean)isEqual:(id)obj;

- (jint)getDifferenceWithLong:(jlong)minuendInstant
                     withLong:(jlong)subtrahendInstant;

- (jlong)getDifferenceAsLongWithLong:(jlong)minuendInstant
                            withLong:(jlong)subtrahendInstant;

- (jlong)getMillisWithInt:(jint)value;

- (jlong)getMillisWithInt:(jint)value
                 withLong:(jlong)instant;

- (jlong)getMillisWithLong:(jlong)value;

- (jlong)getMillisWithLong:(jlong)value
                  withLong:(jlong)instant;

- (jint)getScalar;

- (jlong)getUnitMillis;

- (jint)getValueWithLong:(jlong)duration;

- (jint)getValueWithLong:(jlong)duration
                withLong:(jlong)instant;

- (jlong)getValueAsLongWithLong:(jlong)duration;

- (jlong)getValueAsLongWithLong:(jlong)duration
                       withLong:(jlong)instant;

- (NSUInteger)hash;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeFieldScaledDurationField)

FOUNDATION_EXPORT void OrgJodaTimeFieldScaledDurationField_initWithOrgJodaTimeDurationField_withOrgJodaTimeDurationFieldType_withInt_(OrgJodaTimeFieldScaledDurationField *self, OrgJodaTimeDurationField *field, OrgJodaTimeDurationFieldType *type, jint scalar);

FOUNDATION_EXPORT OrgJodaTimeFieldScaledDurationField *new_OrgJodaTimeFieldScaledDurationField_initWithOrgJodaTimeDurationField_withOrgJodaTimeDurationFieldType_withInt_(OrgJodaTimeDurationField *field, OrgJodaTimeDurationFieldType *type, jint scalar) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeFieldScaledDurationField *create_OrgJodaTimeFieldScaledDurationField_initWithOrgJodaTimeDurationField_withOrgJodaTimeDurationFieldType_withInt_(OrgJodaTimeDurationField *field, OrgJodaTimeDurationFieldType *type, jint scalar);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeFieldScaledDurationField)

#endif

#pragma pop_macro("INCLUDE_ALL_ScaledDurationField")
